### PR TITLE
Ability to embed using a specific relation when there are multiple between tables, fixes #907

### LINKED ISSUE #907: Resource Embedding Unexpected Behavior: table is being treated as pivot
```sql
-- users
create table data.users ( -- df: mult=3.0
  id serial primary key,
....
-- forms
create table data.forms ( -- df: mult=10.0
  id serial primary key,
  user_id integer references data.users(id) default request.user_id(),
....
-- pitches
create table data.pitches ( -- df: mult=100.0
  id serial primary key,
  user_id integer references data.users(id) default request.user_id(),
  form_id integer references data.forms(id) not null,
....
```
http://localhost:8080/rest/users?select=name,forms(name)
creates this query
```sql
SELECT  "api"."users"."name", COALESCE ((SELECT array_to_js on(array_agg(row_to_json("forms"))) 
FROM (SELECT  "api"."forms"."name" FROM  "api"."pitches", "api"."forms"  
WHERE  "api"."forms"."id" = "api"."pitches"."form_id" 
AND  "api"."users"."id" = "api"."pitches"."user_id"  ) "forms"), '[]') 
AS "forms" FROM  "api"."users"
```

### intended behavior:
users (one to many) forms
### recieved:
users (many to many through pitches) forms

### PR DESCRIPTION
**Pull request by ruslantalpa**
*Well, this bothered me more than it should :)*

When embedding parents we had the ability to say which FK to use by using it directly instead of the table name ( `billing_address_id`, `shipping_address_id` )

but when requesting children, there is no such possibility.
This PR adds the possibility to "lock" the path in the other direction like this
`/addresses?select=id,billed:orders.billing_address_id{id},shipped:orders.shipping_address_id{id}`
*the aliases before `:` are not mandatory when there is no collision*

In this case, the part after the `.` is the name of the FK

When there is a many to many relation, it's also possible to select it like so
`/tasks?select=id,users.users_tasks{id}`

In this case the part after the `.` is the name of the "link" table.

PS: I'd like to thank the Academy, Haskell language, and GHC's type-checker without which these types of PRs would not be possible :)

### CODE REVIEW

**Comment by ruslantalpa** [comment]
Let's merge #885 first then i'll rebase. Those openAPI tests take a long time that that pr does a great job of fixing that.

**Comment by begriffs** [comment]
Nice! What happens if somebody puts a nonexistent column name after the dot, or a column that is not part of an FK? Curious how friendly the error will be.

(Also I merged the openapi PR so ready for your rebase)

**Comment by ruslantalpa** [comment]
the error will be could not find relation ...

**Comment by ruslantalpa** [comment]
rebased, CI is running now

**Comment by begriffs** [comment]
Nice feature, nice tests. 🚢  Looks good to me, so you can click squash and merge if you're happy with it.

Too bad it introduces more underscores in the pattern matches, but fixing that doesn't seem straightforward.

File: src/PostgREST/Types.hs [hunk 1]
```diff
@@ -182,7 +182,8 @@ type Field = (FieldName, Maybe JsonPath)
 type Alias = Text
 type Cast = Text
 type NodeName = Text
-type SelectItem = (Field, Maybe Cast, Maybe Alias)
+type RelationDetail = Text
```
Comment (steve-chavez) [inline src/PostgREST/Types.hs]: This type is not clear to me, Relation is already a confusing name since PostgreSQL calls tables and views "relations". Could this name be more precise?

**Comment by ruslantalpa** [comment]
By the time the logic gets to the QueryBuilder module, that last param i added is not used since the information is contained in the `Maybe Relation` type, so yeah it's not very nice, but i think i have an idea of how to refactor so that querybuilder module is not touched.

something like

```haskell
data Rel = R Relation | D RelationDetail
type ReadNode = (ReadQuery, (NodeName, Maybe Rel, Maybe Alias))
```

so that the middle component can hold the info either in `R` or `D` format since it kind of relates to the same thing.

@steve-chavez i'll think about the naming, my thinking was: this information is used in determining the `Relation` component so i called it `RelationDetail`.  Here relation is used in the sens of "what is the relation between this tree node and its parent"
While changing RelationDetail part is relatively easey, i would not go and change the name for Relation type since it's all over the place ...

**Comment by steve-chavez** [comment]
@ruslantalpa The Relation type is definitely not easy to refactor, I was thinking that just a rename of ```RelationDetail``` could be made, into a more obvious type name, something like ```EmbedFK/FKCol/FKName/JoinColumn```, or maybe just leave the type with a comment.

File: src/PostgREST/QueryBuilder.hs [hunk 2]
```diff
@@ -218,7 +218,11 @@ requestToQuery :: Schema -> Bool -> DbRequest -> SqlQuery
 requestToQuery schema isParent (DbRead (Node (Select colSelects tbls logicForest ord range, (nodeName, maybeRelation, _)) forest)) =
   query
   where
-    mainTbl = fromMaybe nodeName (tableName . relTable <$> maybeRelation)
+    -- data RelationInfo = R Relation | D RelationDetail;
+    rir (R r) = Just r
+    rir _ = Nothing
+
+    mainTbl = fromMaybe nodeName (tableName . relTable <$> join (rir <$> maybeRelation))
```
Comment (ruslantalpa) [inline src/PostgREST/QueryBuilder.hs]: anyone has a better idea how to write this (without the rir function ...)?

**Comment by ruslantalpa** [comment]
do the types look better now a bit compared to the previous version?

**Comment by steve-chavez** [comment]
Though there are less wildcard pattern matches now there are unwrapping functions(`rir`, `r`) the former being more easy to understand, the added constructors `R` and `D` are not that meaningful and the QueryBuilder is still modified, overall I think the previous version was clearer, maybe it'll be better to just go back to the previous `ReadNode`(withouth `RelationInfo`) type and add a comment for the `RelationDetail` since is not easy to come with a self-explanatory name for it.

**Comment by ruslantalpa** [comment]
@begriffs feel the same way? I'll reveret. Also not particularily liking these types

**Comment by begriffs** [comment]
Yeah I do think the R and D stuff is pretty terse.

Also I agree with Steve's point that Relation is a pretty overloaded term. Perhaps `FkRelation` in the context of foreign keys would make it more explicit.

**Comment by ruslantalpa** [comment]
OK, i'll revert but leave the Relation type name in places, it would be too much unrelated change for this RP

**Comment by ruslantalpa** [comment]
reverted back

**Comment by ruslantalpa** [comment]
about relationDetail, happy to rename just not sure what it should be.
It does not always hold the name of the FK, sometimes, in many to many it holds the name of the join table, that's why i named it RelationDetail.

any suggestions before i merge this? (adding a comment about the type now)

**Comment by begriffs** [comment]
The new comments are helpful. I'm OK if you merge, unless Steve has any other thoughts.

**Comment by steve-chavez** [comment]
I'm OK as well, the new comments are good enough.
